fastlane_version "1.66.0"

default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean
  end

  desc "Run all the tests"
  lane :test do
    scan(device: "iPhone 6 (8.1)")
  end
end

