require 'securerandom'

fastlane_version "1.66.0"

default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean
  end

  desc "Run all the tests"
  lane :test do
    scan(
      device: "iPhone 6 (8.1)",
      skip_build: true
      )
  end

  desc "Submit a new Beta build to Hockey App"
  lane :beta do

    # keychain_name = "excitebike-certs"

    # create_keychain(
    #   name: keychain_name,
    #   default_keychain: true,
    #   unlock: true,
    #   timeout: 3600,
    #   lock_when_sleeps: true,
    #   password: SecureRandom.base64
    # )

    # # Import distribution certificate
    # import_certificate(
    #   certificate_path: "fastlane/Certificates/distribution.p12",
    #   certificate_password: ENV["KEY_PASSWORD"],
    #   keychain_name: keychain_name
    #   )

    # # Fetch provisioning profile
    # sigh(
    #   adhoc: true,
    #   provisioning_name: "Excitebike Ad Hoc"
    #   )

    cert
    sigh(
      adhoc: true,
      force: true
    )

    increment_build_number(build_number: number_of_commits)

    # Build
    gym(
      configuration: "Ad Hoc",
      sdk: "iphoneos9.2",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      use_legacy_build_api: true,
      export_method: "enterprise"
      )

    # Push to Hockey
    hockey(
      api_token: ENV["HOCKEY_API_TOKEN"],
      public_identifier: ENV["HOCKEY_APP_ID"],
      notify: '0',
      status: '2',
      notes: last_git_commit[:message] + "\n(Uploaded automatically via fastlane)"
      )

    delete_keychain(
      name: keychain_name
      )
  end
end
