require 'securerandom'

fastlane_version "1.66.0"

default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean
  end

  desc "Run all the tests"
  lane :test do
    scan(
      device: "iPhone 6 (8.1)",
      skip_build: true
      )
  end

  desc "Sync certificates"
  lane :match do
    match(
      type: "appstore",
      app_identifier: "com.pairinggroup.Excitebike.app-store"
    )
    match(
      type: "adhoc",
      app_identifier: "com.pairinggroup.Excitebike.ad-hoc"
    )
    match(
      type: "development",
      app_identifier: "com.pairinggroup.Excitebike.development"
    )
  end

  desc "Submit a new Beta build to Hockey App"
  lane :beta do

    match(
      type: "adhoc",
      app_identifier: "com.pairinggroup.Excitebike.ad-hoc",
      readonly: true
    )

    increment_build_number(build_number: number_of_commits)

    # Build
    gym(
      configuration: "Ad Hoc",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      use_legacy_build_api: true,
      export_method: "enterprise"
      )

    # Push to Hockey
    hockey(
      api_token: ENV["HOCKEY_API_TOKEN"],
      public_identifier: ENV["HOCKEY_APP_ID"],
      notify: '0',
      status: '2',
      notes: last_git_commit[:message] + "\n(Uploaded automatically via fastlane)"
      )

  end
end
